# LISTA 10 -  LIBRERÍA NUMPY

## <ins>Ejercicios Obligatorios </ins>

Ejercicios de Irune Guinea 🚀

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas import Series, DataFrame

## EJERCICIO 1

Crea un array unidimensional de 9 elementos y transfórmalo en un array 3D. Muestra la dimensión y la shape antes y después del reshape.

In [5]:

# Creamos el array 1D
arr_1d = np.arange(9)

print("Array unidimensional:")
print(arr_1d)
# Imprimimos la shape actual
print("\nShape antes del reshape:", arr_1d.shape)

# Transformar a 3D
arr_3d = arr_1d.reshape((3, 3))

print("\nArray 3D")
print(arr_3d)
print("\nShape después del reshape:", arr_3d.shape)

Array unidimensional:
[0 1 2 3 4 5 6 7 8]

Shape antes del reshape: (9,)

Array 3D
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Shape después del reshape: (3, 3)


## EJERCICIO 2

Dados los arrays 2D ```[[-6, 5], [-4, 3], [-2, 1]] y [[1, 2], [3, 4], [5, 6]]```, concaténalos de modo que obtengas el array ```[[1, 2, -6, -5], [3, 4, -4, -3], [5, 6, -2, -1]]```

In [6]:
import numpy as np

# Definir los dos arrays
array1 = np.array([[-6, 5], [-4, 3], [-2, 1]])
array2 = np.array([[1, 2], [3, 4], [5, 6]])

# función concatenate para concatenar :)
result = np.concatenate((array2, array1), axis=1)

print(result)

[[ 1  2 -6  5]
 [ 3  4 -4  3]
 [ 5  6 -2  1]]


## EJERCICIO 3

Dado el array 2D ```[["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"], ["hoja", "gato", "elle"]]```, busca las palabras que sean palíndromos. Necesitarás una función universal.

In [7]:

# Creo una copia al reves con [::-1] y lo comparo con el string, si son iguales es palíndromo
def es_palindromo(palabra):
    
    return palabra == palabra[::-1]

array_2d = [["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"], ["hoja", "gato", "elle"]]
# iterar sobre las filas del array, y en cada fila itera sobre las palabras y llama 
# a la función es palindromo, almacena los palindromos
palindromos = [word for row in array_2d for word in row if es_palindromo(word)]

print("Palabras palíndromas:", palindromos)

Palabras palíndromas: ['ala', 'kayak', 'elle']


## EJERCICIO 4

Crea un minijuego que piense un número aleatorio entre 1 y 10 y, hasta que no lo aciertes, te pida un número del 1 al 10. Cuando aciertes, tendrá que devolver el número de intentos y la frase: “¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el {}”. En caso de que falles, el juego deberá mostrar la frase “¡Has fallado! ¡Prueba otra vez!”

In [12]:
import numpy as np

# la respuesta aleatoria
numero_correcto = np.random.randint(1, 11)
# defino esto para no hacer un while true, así la primera vez entrará siempre
intento = "-1"
while int(intento) != numero_correcto:
    intento = input("Adivina un número del 1 al 10: ")
    # una pequeña validación :)
    while not intento.isdigit() or not 1 <= int(intento) <= 10:
        intento = input("Por favor, introduce un número entero entre 1 y 10.")        
    # comprobar si es correcto
    if int(intento) == numero_correcto:
        print(f"¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el {numero_correcto}")
    else:
        print("¡Has fallado! ¡Prueba otra vez!")

¡Has fallado! ¡Prueba otra vez!
¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el 5


## EJERCICIO 5

Crea un minijuego que piense un array 1D aleatorio de 5 elementos. Los elementos serán números enteros entre 1 y 20. Para cada intento, primero tendrá que pedir 5 números enteros del 1 al 20. El juego nos tendrá que decir cuántos números del array hemos acertado y cuántos números del array están bien colocados. El juego no termina hasta que no se hayan acertado todos los números pensados en la posición correspondiente. Al acabar, se tendrá que mostrar la frase: “¡¡¡ENHORABUENA!!! Has acertado el array que había pensado: {}”

In [ ]:
import numpy as np

# Array random de 5 números enteros del 1 al 20
def arrayRandom():
    return np.random.randint(1, 21, size=5)

# Comprobar si es correcto (equal compara posición a posición)
# y devuelvo cuantos están en posición correcta
def comprobar(intento, resultado_correcto):
    es_correcto = np.sum(np.equal(intento, resultado_correcto))
    return es_correcto

# La función del juego :)
def wordle():
    print("Wordle pero con números")
    print("Introduce un array aleatorio de 5 números enteros entre 1 y 20.")
    
    resultado_correcto = arrayRandom()
    
    # Al principio las posiciones correctas serán 0
    # así entrará siempre al bucle la primera vez
    # sin usar un while true
    posiciones_correctas = 0
    
    while posiciones_correctas != 5:
        intento = []
        # lo mismo con intento, para que entre la primera vez
        for i in range(5): # por que son 5 números
            while len(intento)!=5:
                try:
                    num = int(input(f"Introduce el número {i+1} (del 1 al 20): "))
                    if 1 <= num <= 20:
                        intento.append(num)
                        break
                    else:
                        # Unas pequeñas validaciones :)
                        print("Número fuera del rango. Intenta de nuevo.")
                except ValueError:
                    print("No es un número válido. Intenta de nuevo.")

        # para que me quede un poco mas chulo
        print("----------------------------------")
              
        # validar que estén entre 1 y 20
        if not np.all((np.array(intento) >= 1) & (np.array(intento) <= 20)):
            print("Los números tienen que estar entre 1 y 20.")
            continue
        
        posiciones_correctas = comprobar(intento, resultado_correcto)
        print(f"Intento actual: {intento}")
        print(f"Números correctos en posición: {posiciones_correctas}")
        
        # Si son 5 hemos acabado
        if posiciones_correctas == 5:
            print("\n¡!!ENHORABUENA!!! Has acertado el array que había pensado:")
            print(resultado_correcto)
            break
    
# para llamar a la función del juego
if __name__ == "__main__":
    wordle()

## EJERCICIO 6

A partir de la lista ```[-3, -2, -1, 0, 1, 2, 3]```, genera dos arrays aleatorios 2D de size = (3, 4) y súmalos.

In [11]:
import numpy as np

lista = [-3, -2, -1, 0, 1, 2, 3]

# Crear los arrays aleatorios de (3,4)
array1 = np.random.choice(lista, size=(3, 4))
array2 = np.random.choice(lista, size=(3, 4))

# Suma de arrays
suma_arrays = array1 + array2

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nSuma de Arrays:")
print(suma_arrays)

Array 1:
[[ 2  0  3  1]
 [-1 -1 -1  0]
 [-3 -1 -1  2]]

Array 2:
[[-2  0 -1 -3]
 [-1 -2  0  0]
 [-3  2  2  3]]

Suma de Arrays:
[[ 0  0  2 -2]
 [-2 -3 -1  0]
 [-6  1  1  5]]


## <ins>Ejercicios Opcionales </ins>

🧐 Por si vienen bien para el examen 

## EJERCICIO 7

Dado el array 2D ```[[1, 2, 3],[-1, 0, 1], [4, 5, 6], [-4, 0, 4], [3, 2, 1], [-3, 0, 3]]``` divídelo en 3 arrays 2D.

In [1]:
import numpy as np

# El array 2D
array_2d = np.array([[1, 2, 3], [-1, 0, 1], [4, 5, 6], [-4, 0, 4], [3, 2, 1], [-3, 0, 3]])

# Extraigo las filas y las columnas con shape, como la primera posición de la respuesta
# son las filas asigno a num_filas, la segunda son columnas, no los necesito pero tengo que asignar
# para sacarlo así 
num_filas, num_columnas = array_2d.shape

# cada subarray tendra este número de filas
num_fila_sub = num_filas // 3

# Divido el array usando el número de filas que van a tener
subarray1 = array_2d[:num_fila_sub]
subarray2 = array_2d[num_fila_sub:2*num_fila_sub]
subarray3 = array_2d[2*num_fila_sub:]

print("Subarray 1:")
print(subarray1)
print("\nSubarray 2:")
print(subarray2)
print("\nSubarray 3:")
print(subarray3)

Subarray 1:
[[ 1  2  3]
 [-1  0  1]]

Subarray 2:
[[ 4  5  6]
 [-4  0  4]]

Subarray 3:
[[ 3  2  1]
 [-3  0  3]]


## EJERCICIO 8

Crea una función universal que dado un array de strings devuelva el número total de vocales de cada string.

In [5]:
def contar_vocales(array_de_strings):
    # hay que definir cuales son las vocales
    # recordar que a y A no son lo mismo
    # tienen diferente código ASCII :)
    vocales = 'aeiouAEIOU'

    # contar me cuenta las vocales de un string
    # itera sobre las letras, y si la letra está en vocales
    # suma uno
    def contar(palabra):
        return sum(1 for letra in palabra if letra in vocales)
    
    # itero sobre cada string del array y le aplico contar
    return [contar(palabra) for palabra in array_de_strings]

array_de_strings = ["Aupiii", "zelan", "zAUdete", "gaur"]
cuantas = contar_vocales(array_de_strings)
print(cuantas)

[5, 2, 4, 2]
