# LISTA 10 -  LIBRERÍA NUMPY

## <ins>Ejercicios Obligatorios </ins>

In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas import Series, DataFrame

## EJERCICIO 1

Crea un array unidimensional de 9 elementos y transfórmalo en un array 3D. Muestra la dimensión y la shape antes y después del reshape.

In [5]:

arr_1d = np.arange(9)

print("Array unidimensional:")
print(arr_1d)
print("\nShape antes del reshape:", arr_1d.shape)

arr_3d = arr_1d.reshape((3, 3))

print("\nArray 3D")
print(arr_3d)
print("\nShape después del reshape:", arr_3d.shape)

Array unidimensional:
[0 1 2 3 4 5 6 7 8]

Shape antes del reshape: (9,)

Array 3D
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Shape después del reshape: (3, 3)


## EJERCICIO 2

Dados los arrays 2D ```[[-6, 5], [-4, 3], [-2, 1]] y [[1, 2], [3, 4], [5, 6]]```, concaténalos de modo que obtengas el array ```[[1, 2, -6, -5], [3, 4, -4, -3], [5, 6, -2, -1]]```

In [6]:
import numpy as np

array1 = np.array([[-6, 5], [-4, 3], [-2, 1]])
array2 = np.array([[1, 2], [3, 4], [5, 6]])


result = np.concatenate((array2, array1), axis=1)

print(result)

[[ 1  2 -6  5]
 [ 3  4 -4  3]
 [ 5  6 -2  1]]


## EJERCICIO 3

Dado el array 2D ```[["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"], ["hoja", "gato", "elle"]]```, busca las palabras que sean palíndromos. Necesitarás una función universal.

In [7]:

def es_palindromo(palabra):
    
    return palabra == palabra[::-1]

array_2d = [["ala", "delfín", "arroz"], ["cena", "kayak", "picnic"], ["hoja", "gato", "elle"]]

palindromos = [word for row in array_2d for word in row if es_palindromo(word)]

print("Palabras palíndromas:", palindromos)

Palabras palíndromas: ['ala', 'kayak', 'elle']


## EJERCICIO 4

Crea un minijuego que piense un número aleatorio entre 1 y 10 y, hasta que no lo aciertes, te pida un número del 1 al 10. Cuando aciertes, tendrá que devolver el número de intentos y la frase: “¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el {}”. En caso de que falles, el juego deberá mostrar la frase “¡Has fallado! ¡Prueba otra vez!”

In [12]:
import numpy as np

numero_correcto = np.random.randint(1, 11)
intento = "-1"
while int(intento) != numero_correcto:
    intento = input("Adivina un número del 1 al 10: ")
        
    while not intento.isdigit() or not 1 <= int(intento) <= 10:
        intento = input("Por favor, introduce un número entero entre 1 y 10.")        
        
    if int(intento) == numero_correcto:
        print(f"¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el {numero_correcto}")
    else:
        print("¡Has fallado! ¡Prueba otra vez!")

¡Has fallado! ¡Prueba otra vez!
¡¡¡ENHORABUENA!!! Has acertado el número que había pensado: el 5


## EJERCICIO 5

Crea un minijuego que piense un array 1D aleatorio de 5 elementos. Los elementos serán números enteros entre 1 y 20. Para cada intento, primero tendrá que pedir 5 números enteros del 1 al 20. El juego nos tendrá que decir cuántos números del array hemos acertado y cuántos números del array están bien colocados. El juego no termina hasta que no se hayan acertado todos los números pensados en la posición correspondiente. Al acabar, se tendrá que mostrar la frase: “¡¡¡ENHORABUENA!!! Has acertado el array que había pensado: {}”

In [ ]:
import numpy as np

def arrayRandom():
    return np.random.randint(1, 21, size=5)

def comprobar(intento, resultado_correcto):
    es_correcto = np.sum(np.equal(intento, resultado_correcto))
    return es_correcto

def wordle():
    print("Wordle pero con números")
    print("Introduce un array aleatorio de 5 números enteros entre 1 y 20.")
    
    resultado_correcto = arrayRandom()
    
    posiciones_correctas = 0
    
    while posiciones_correctas != 5:
        intento = []
        for i in range(5):
            while len(intento)!=5:
                try:
                    num = int(input(f"Introduce el número {i+1} (del 1 al 20): "))
                    if 1 <= num <= 20:
                        intento.append(num)
                        break
                    else:
                        print("Número fuera del rango. Intenta de nuevo.")
                except ValueError:
                    print("No es un número válido. Intenta de nuevo.")
        
        print("----------------------------------")
              
        
        if not np.all((np.array(intento) >= 1) & (np.array(intento) <= 20)):
            print("Los números tienen que estar entre 1 y 20.")
            continue
        
        posiciones_correctas = comprobar(intento, resultado_correcto)
        print(f"Intento actual: {intento}")
        print(f"Números correctos en posición: {posiciones_correctas}")
        
        if posiciones_correctas == 5:
            print("\n¡!!ENHORABUENA!!! Has acertado el array que había pensado:")
            print(resultado_correcto)
            break
    

if __name__ == "__main__":
    wordle()

## EJERCICIO 6

A partir de la lista ```[-3, -2, -1, 0, 1, 2, 3]```, genera dos arrays aleatorios 2D de size = (3, 4) y súmalos.

In [11]:
import numpy as np

lista = [-3, -2, -1, 0, 1, 2, 3]

array1 = np.random.choice(lista, size=(3, 4))
array2 = np.random.choice(lista, size=(3, 4))

suma_arrays = array1 + array2

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)
print("\nSuma de Arrays:")
print(suma_arrays)

Array 1:
[[ 2  0  3  1]
 [-1 -1 -1  0]
 [-3 -1 -1  2]]

Array 2:
[[-2  0 -1 -3]
 [-1 -2  0  0]
 [-3  2  2  3]]

Suma de Arrays:
[[ 0  0  2 -2]
 [-2 -3 -1  0]
 [-6  1  1  5]]


## <ins>Ejercicios Opcionales </ins>

## EJERCICIO 7

Dado el array 2D ```[[1, 2, 3],[-1, 0, 1], [4, 5, 6], [-4, 0, 4], [3, 2, 1], [-3, 0, 3]]``` divídelo en 3 arrays 2D.

## EJERCICIO 8

Crea una función universal que dado un array de strings devuelva el número total de vocales de cada string.